sonar.projectKey=nabhat_graphify-sfcc2
sonar.organization=nabhat

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=graphify-sfcc2
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file.
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
